#!/bin/bash
# SPDX-License-Identifier: GPL-3.0+
# Copyright (C) 2026 Mohamed Khalfella

. tests/nvme/rc
. common/ublk

DESCRIPTION="Test injecting delay on nvme-target backstore and expect no corruption"

requires() {
	_nvme_requires
	_have_loop
	_have_ublk
	_have_module_param_value nvme_core multipath Y
	_require_nvme_trtype_is_fabrics
	_have_src_program nvme-ghost-write-detector
}

set_conditions() {
	_set_nvme_trtype "$@"
}

count_paths_to_subsystem() {
	local subsysnqn="$1"
	local dev count

	count=0
	for dev in /sys/class/nvme/nvme*; do
		[[ -e "${dev}/subsysnqn" ]] || continue
		[[ "$(cat "${dev}/subsysnqn")" == "${subsysnqn}" ]] || continue
		count=$(( count + 1 ))
	done
	echo "${count}"
}

set_io_timeout_of_subsystem() {
	local subsysnqn="$1"
	local timeout="$2"
	local dev

	for dev in /sys/class/nvme/nvme*; do
		[[ -e "${dev}/subsysnqn" ]] || continue
		[[ "$(cat "${dev}/subsysnqn")" == "${subsysnqn}" ]] || continue
		if ! echo "${timeout}" > "${dev}/io_timeout" 2> /dev/null; then
			echo "FAIL: can not set io_timeout on ${dev##*/}"
			return 1
		fi
	done
}

test() {
	echo "Running ${TEST_NAME}"

	local ns port nr_paths
	local attr_cqt
	local -a ports

	if ! _init_ublk; then
		return 1
	fi

	truncate -s "${NVME_IMG_SIZE}" "${TMPDIR}/ublk-img"
	if ! ${UBLK_PROG} add -t loop -f "${TMPDIR}/ublk-img" -n 0 > "$FULL" 2>&1; then
		echo "fail to add ublk device"
		_exit_ublk
		return 1
	fi
	udevadm settle

	_setup_nvmet
	_nvmet_target_setup --ports 2 --blkdev none
	_create_nvmet_ns --blkdev /dev/ublkb0 \
		--uuid "${def_subsys_uuid}" > /dev/null

	_get_nvmet_ports "${def_subsysnqn}" ports
	echo "Target ports: ${#ports[@]}"
	for port in "${ports[@]}"; do
		_nvme_connect_subsys --port "${port}"
	done

	nr_paths=$(count_paths_to_subsystem "${def_subsysnqn}")
	if ((  nr_paths != 2 )); then
		echo "FAIL: expected 2 paths, found ${nr_paths}"
	fi

	set_io_timeout_of_subsystem "${def_subsysnqn}" 2000

	if ! ${UBLK_PROG} inject -n 0 -o write -d 4 -c 1 >> "$FULL" 2>&1; then
		echo "FAIL: can not inject write delay"
	fi

	ns=$(_find_nvme_ns "${def_subsys_uuid}")
	"$SRCDIR/nvme-ghost-write-detector" "/dev/${ns}"

	_nvme_disconnect_subsys
	_nvmet_target_cleanup
	_exit_ublk
	echo "Test complete"
}
